name: "our-famuly-project-infra"

services:
  database:
    image: postgres:latest
    container_name: our-family-database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      our-family-network:

  pgadmin:
    image: dpage/pgadmin4
    container_name: our-family-pgadmin
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      our-family-network:

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      our-family-network:

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      our-family-network:

networks:
  our-family-network:

volumes:
  redis-insight:
